-- CreateEnum
CREATE TYPE "Department" AS ENUM ('TECHNICAL_INFRASTRUCTURE', 'WATER_SANITATION', 'ENVIRONMENT_WASTE', 'ELECTRICITY_LIGHTING', 'DISASTER_PUBLIC_SAFETY', 'ADMINISTRATION');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "department" "Department",
ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true;
